spring.application.name=UserService
server.port=8081

spring.data.mongodb.uri=mongodb://localhost:27017/userdb

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# JWT config
jwt.secret=mySuperSecretKey
jwt.expiration=900000       # 15 minutes in ms
jwt.refresh-expiration=604800000  # 7 days in ms


# Social login configs (for future step)
# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=openid,email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/oauth2/callback/google

# Facebook OAuth2
spring.security.oauth2.client.registration.facebook.client-id=YOUR_FACEBOOK_CLIENT_ID
spring.security.oauth2.client.registration.facebook.client-secret=YOUR_FACEBOOK_CLIENT_SECRET
spring.security.oauth2.client.registration.facebook.scope=email,public_profile
spring.security.oauth2.client.registration.facebook.redirect-uri=http://localhost:8081/oauth2/callback/facebook