server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins: ${FRONTEND_ORIGIN:http://localhost:4200}
            allowed-methods: GET,POST,PUT,DELETE,OPTIONS
            allowed-headers: '*'
            allow-credentials: true
      routes:

        - id: auth-public
          uri: lb://UserService
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /users/${segment}

        - id: user-service
          uri: lb://UserService
          predicates:
            - Path=/api/users/**
          filters:
            - JwtAuthFilter
            - RewritePath=/api/users/(?<segment>.*), /users/${segment}
        
        - id: product-public-list
          uri: lb://ProductService
          predicates:
            - Path=/api/products
            - Method=GET

        - id: product-public-detail
          uri: lb://ProductService
          predicates:
            - Path=/api/products/{id}
            - Method=GET

        - id: product-protected
          uri: lb://ProductService
          predicates:
            - Path=/api/products/**
            - Method=POST,PUT,DELETE
          filters:
            - JwtAuthFilter

        - id: media-public-serve
          uri: lb://MediaService
          predicates:
            - Path=/api/media/{id}
            - Method=GET

        - id: media-service
          uri: lb://MediaService
          predicates:
            - Path=/api/media/**
          filters:
            - JwtAuthFilter
